# Generated by Django 3.2 on 2023-03-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='made_by_user',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
