# Generated by Django 3.2 on 2023-03-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_user_made_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='made_by_user',
            field=models.BooleanField(null=True),
        ),
    ]
