# Generated by Django 3.2 on 2023-03-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_user_made_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='made_by_user',
        ),
    ]
